# Generated by Django 5.1.4 on 2024-12-07 16:43

import datetime
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='data_published',
            field = models.DateTimeField(
            default=django.utils.timezone.now,verbose_name='Дата публикации'
            ),
        ),
    ]
